apiVersion: v2
name: flask-app
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "0.1.0"
dependencies:
  - name: app-generic
    version: 0.1.0
    repository: "file://../app-generic"
