name: Helm Chart Release Trigger

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

  workflow_dispatch:
    inputs:
      version:
        description: "Manual test version"
        required: true
        default: "0.0.0"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: igorsilva-dev/helm-charts
          path: helm-charts
          ref: main

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update Chart.yaml version
        run: |
          yq -i '.version = "${{ inputs.version }}"' charts/${{ inputs.application }}/Chart.yaml

      - name: debug GH_PAT
        run: |
          if [ -z "$GH_PAT" ]; then
            echo "GH_PAT is EMPTY"
          else
            echo "GH_PAT length is: ${#GH_PAT}"
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |          
          git config user.name "igorsilva-dev"
          git config user.email "dev@igorsilva.dev"

          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/igorsilva-dev/helm-charts.git

          git add charts/${{ inputs.application }}/Chart.yaml
          git commit -m "chore: bump ${{ inputs.application }} chart version to ${{ inputs.version }}" || true
          git push origin main


      - name: Show version received
        run: |
          echo "Version received (changed): ${{ inputs.version }}"

      - name: Show version received
        run: |
          echo "Version received (changed): ${{ inputs.version }}"

